import type { ClientRecord } from '@/types/clients';
import type { LeadRecord } from '@/types/leads';
import type { PaymentLinkRecord } from '@/types/payments';
import type { PreEventRecord } from '@/types/pre-events';
import type { QuoteRecord } from '@/types/quotes';
import type { EmailTemplatePurpose } from '@/types/email-templates';
import { resolveCommunicationLanguage } from '@/services/communication/language';
import { getActiveEmailTemplateSelectionByPurpose } from '@/services/email-templates/queries';
import { renderEmailTemplate } from '@/services/email-templates/render';
import { buildQuoteEmailDraft } from '@/services/quotes/email-template';

export async function composeQuotePurposeEmail({
  quote,
  lead,
  client,
  preEvent,
  paymentLink,
  paymentLinkStatus,
  isAutoGeneratedLink,
  purpose,
}: {
  quote: QuoteRecord;
  lead: LeadRecord;
  client: ClientRecord | null;
  preEvent: PreEventRecord | null;
  paymentLink: PaymentLinkRecord | null;
  paymentLinkStatus: 'existing' | 'auto_generated' | 'missing';
  isAutoGeneratedLink: boolean;
  purpose: EmailTemplatePurpose;
}) {
  const draft = await buildQuoteEmailDraft({
    quote,
    lead,
    client,
    preEvent,
    paymentLink,
    paymentLinkStatus,
    isAutoGeneratedLink,
  });

  const communicationLanguage = resolveCommunicationLanguage({
    clientPreferredLanguage: client?.preferred_language,
    leadLanguage: lead.language,
  });

  const templateSelection = await getActiveEmailTemplateSelectionByPurpose(purpose, communicationLanguage.language);
  const renderedTemplate = templateSelection.template
    ? renderEmailTemplate(templateSelection.template, {
      client_name: draft.recipientName,
      event_date: draft.eventDetails.date,
      event_time: draft.eventDetails.time,
      quote_total: new Intl.NumberFormat('es-MX', { style: 'currency', currency: 'MXN' }).format(draft.quoteSummary.totalAmount),
      payment_link: draft.paymentLink?.url ?? '',
      balance_due: draft.paymentRequest.estimatedBalanceLabel,
      deposit_amount: draft.paymentRequest.amountLabel,
      event_address: draft.eventDetails.address,
      service_label: draft.eventDetails.serviceLabel,
      company_name: draft.branding.companyName,
      zelle_instructions: draft.zelle.instructions,
    })
    : null;

  const subject = renderedTemplate?.subject?.trim() ? renderedTemplate.subject : draft.subject;
  const html = renderedTemplate?.html?.trim() ? renderedTemplate.html : draft.html;
  const text = renderedTemplate?.text?.trim() ? renderedTemplate.text : draft.text;

  const operatorMessage = templateSelection.resolution === 'missing'
    ? `No existe plantilla activa para ${purpose} en el idioma solicitado ni en el fallback. Se enviará el draft base actual.`
    : templateSelection.resolution === 'default_fallback'
      ? `No existe plantilla activa para ${templateSelection.requestedLanguage.toUpperCase()}. Se usará fallback ${templateSelection.resolvedLanguage?.toUpperCase()}.`
      : null;

  return {
    draft,
    communicationLanguage,
    templateSelection,
    renderedTemplate,
    subject,
    html,
    text,
    operatorMessage,
  };
}

export async function composeQuoteDeliveryEmail(args: Omit<Parameters<typeof composeQuotePurposeEmail>[0], 'purpose'>) {
  return composeQuotePurposeEmail({ ...args, purpose: 'quote_delivery' });
}
