import type { ClientRecord } from '@/types/clients';
import type { LeadRecord } from '@/types/leads';
import type { PaymentLinkRecord } from '@/types/payments';
import type { PreEventRecord } from '@/types/pre-events';
import type { QuoteEmailDraft } from '@/types/quote-emails';
import type { QuoteRecord } from '@/types/quotes';
import { getQuoteCommercialPaymentMode } from '@/services/quotes/payment-mode';
import { getBusinessSettings } from '@/services/business-settings/queries';

function formatCurrency(value: number | string | null | undefined) {
  const parsed = Number(value ?? 0);
  if (!Number.isFinite(parsed)) return '$0.00 MXN';
  return new Intl.NumberFormat('es-MX', { style: 'currency', currency: 'MXN' }).format(parsed);
}

function formatDate(date: string | null | undefined) {
  if (!date) return 'Por confirmar';
  return new Intl.DateTimeFormat('es-MX', { dateStyle: 'full' }).format(new Date(`${date}T00:00:00`));
}

function normalizeEmail(value: string | null | undefined) {
  return String(value ?? '').trim();
}

function normalizeName(value: string | null | undefined) {
  return String(value ?? '').trim();
}

function isValidEmail(value: string) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
}

export async function buildQuoteEmailDraft({
  quote,
  lead,
  client,
  preEvent,
  paymentLink,
  paymentLinkStatus = 'existing',
  isAutoGeneratedLink = false,
}: {
  quote: QuoteRecord;
  lead: LeadRecord;
  client: ClientRecord | null;
  preEvent: PreEventRecord | null;
  paymentLink: PaymentLinkRecord | null;
  paymentLinkStatus?: 'existing' | 'auto_generated' | 'missing';
  isAutoGeneratedLink?: boolean;
}): Promise<QuoteEmailDraft> {
  const settings = await getBusinessSettings();
  const branding = {
    companyName: settings.company_name,
    websiteUrl: settings.website_url,
    logoUrl: settings.logo_url,
    zelleRecipientName: settings.zelle_recipient_name,
    zelleRecipientContact: settings.zelle_recipient_contact,
    zelleInstructions: settings.zelle_instructions,
  };
  const recipientName = normalizeName(client?.full_name) || normalizeName(lead.full_name) || 'Cliente';
  const toEmail = normalizeEmail(client?.email) || normalizeEmail(lead.email);

  const eventDate = preEvent?.confirmed_date ?? lead.tentative_event_date;
  const eventTime = preEvent?.confirmed_time ?? lead.tentative_event_time;
  const eventAddress = preEvent?.location ?? lead.location ?? client?.location ?? 'Por confirmar';
  const serviceLabel = preEvent?.booked_service ?? lead.service_interest ?? lead.event_type ?? 'Servicio por confirmar';
  const guestCount = preEvent?.confirmed_guests ?? lead.guest_count;
  const paymentRequest = getQuoteCommercialPaymentMode(quote);

  const paymentModeLabel = paymentLink?.payment_mode === 'full' ? 'Pago completo' : paymentRequest.modeLabel;
  const paymentAmount = paymentLink ? formatCurrency(paymentLink.amount_to_charge) : paymentRequest.amountToChargeLabel;

  const subject = `Cotización ${branding.companyName} #${quote.id.slice(0, 8)} · ${recipientName}`;

  const paymentSection = paymentLink
    ? `
      <div style="margin-top:20px;padding:16px;border:1px solid #e2e8f0;border-radius:12px;background:#f8fafc;">
        <h3 style="margin:0 0 8px 0;color:#0f172a;">Pago en línea</h3>
        <p style="margin:0 0 10px 0;color:#334155;">Puedes realizar tu ${paymentModeLabel.toLowerCase()} directamente aquí:</p>
        <p style="margin:0 0 10px 0;"><a href="${paymentLink.external_url}" style="display:inline-block;padding:10px 16px;background:#0f172a;color:#ffffff;text-decoration:none;border-radius:10px;font-weight:600;">Pagar ahora</a></p>
        <p style="margin:0;color:#475569;font-size:13px;">Monto del paso actual: <strong>${paymentAmount}</strong></p>
        <p style="margin:8px 0 0 0;color:#475569;font-size:13px;">Saldo restante estimado después de este paso: <strong>${formatCurrency(quote.estimated_balance)}</strong></p>
        <p style="margin:8px 0 0 0;color:#64748b;font-size:12px;">${
          isAutoGeneratedLink
            ? 'Este link fue generado automáticamente para agilizar tu confirmación.'
            : 'Este link corresponde al método de cobro ya preparado para tu cotización.'
        }</p>
      </div>
    `
    : `
      <div style="margin-top:20px;padding:16px;border:1px dashed #cbd5e1;border-radius:12px;background:#f8fafc;">
        <h3 style="margin:0 0 8px 0;color:#0f172a;">Opciones de pago</h3>
        <p style="margin:0;color:#475569;">Si deseas pagar en línea, responde este correo y te compartimos de inmediato tu link de pago personalizado.</p>
      </div>
    `;

  const zelleSection = `
    <div style="margin-top:20px;padding:16px;border:1px solid #ede9fe;border-radius:12px;background:#faf5ff;">
      <h3 style="margin:0 0 8px 0;color:#581c87;">Pago por Zelle</h3>
      <p style="margin:0;color:#6b21a8;">${branding.zelleInstructions}</p>
      ${
        branding.zelleRecipientName || branding.zelleRecipientContact
          ? `<p style="margin:10px 0 0 0;color:#4c1d95;font-size:13px;">
              ${
                branding.zelleRecipientName
                  ? `Receptor: <strong>${branding.zelleRecipientName}</strong>`
                  : ''
              }
              ${
                branding.zelleRecipientContact
                  ? `${branding.zelleRecipientName ? ' · ' : ''}Dato Zelle: <strong>${branding.zelleRecipientContact}</strong>`
                  : ''
              }
            </p>`
          : ''
      }
    </div>
  `;

  const html = `
  <div style="font-family:Inter,Arial,sans-serif;background:#f1f5f9;padding:24px;">
    <div style="max-width:680px;margin:0 auto;background:#ffffff;border-radius:16px;padding:24px;border:1px solid #e2e8f0;">
      <div style="display:flex;align-items:center;gap:12px;margin-bottom:14px;">
        ${branding.logoUrl ? `<img src="${branding.logoUrl}" alt="${branding.companyName}" style="max-height:42px;width:auto;display:block;" />` : ''}
        <div>
          <p style="margin:0;color:#0f172a;font-weight:700;">${branding.companyName}</p>
          <p style="margin:0;color:#475569;font-size:13px;"><a href="${branding.websiteUrl}" style="color:#475569;text-decoration:underline;">${branding.websiteUrl}</a></p>
        </div>
      </div>
      <p style="margin:0 0 8px 0;color:#334155;">Hola ${recipientName},</p>
      <p style="margin:0 0 16px 0;color:#334155;">¡Gracias por considerar a <strong>${branding.companyName}</strong>! Te compartimos el resumen de tu cotización:</p>

      <div style="padding:16px;border-radius:12px;background:#0f172a;color:#ffffff;">
        <h2 style="margin:0 0 8px 0;font-size:20px;">Cotización #${quote.id.slice(0, 8)}</h2>
        <p style="margin:0;font-size:14px;color:#cbd5e1;">Estado actual: ${quote.status}</p>
      </div>

      <div style="margin-top:20px;padding:16px;border:1px solid #e2e8f0;border-radius:12px;">
        <h3 style="margin:0 0 10px 0;color:#0f172a;">Resumen económico</h3>
        <p style="margin:4px 0;color:#334155;">Subtotal: <strong>${formatCurrency(quote.subtotal)}</strong></p>
        <p style="margin:4px 0;color:#334155;">Descuento: <strong>${formatCurrency(quote.discount_amount)}</strong></p>
        <p style="margin:4px 0;color:#334155;">Total final: <strong>${formatCurrency(quote.total_amount)}</strong></p>
        <p style="margin:4px 0;color:#334155;">Depósito esperado: <strong>${formatCurrency(quote.expected_deposit)}</strong></p>
      </div>

      <div style="margin-top:20px;padding:16px;border:1px solid #e2e8f0;border-radius:12px;">
        <h3 style="margin:0 0 10px 0;color:#0f172a;">Detalles del evento</h3>
        <p style="margin:4px 0;color:#334155;">Fecha: <strong>${formatDate(eventDate)}</strong></p>
        <p style="margin:4px 0;color:#334155;">Hora: <strong>${eventTime ?? 'Por confirmar'}</strong></p>
        <p style="margin:4px 0;color:#334155;">Dirección: <strong>${eventAddress}</strong></p>
        <p style="margin:4px 0;color:#334155;">Invitados: <strong>${guestCount ?? 'Por confirmar'}</strong></p>
        <p style="margin:4px 0;color:#334155;">Servicio: <strong>${serviceLabel}</strong></p>
      </div>

      ${paymentSection}
      ${zelleSection}

      <p style="margin-top:24px;color:#475569;">Si tienes dudas o quieres ajustar algún detalle, responde este correo y con gusto te ayudamos.</p>
      <p style="margin:8px 0 0 0;color:#0f172a;font-weight:600;">Equipo ${branding.companyName}</p>
    </div>
  </div>
  `.trim();

  const text = [
    `Hola ${recipientName},`,
    `Te compartimos el resumen de tu cotización de ${branding.companyName}.`,
    `Cotización #${quote.id.slice(0, 8)}`,
    `Subtotal: ${formatCurrency(quote.subtotal)}`,
    `Descuento: ${formatCurrency(quote.discount_amount)}`,
    `Total final: ${formatCurrency(quote.total_amount)}`,
    `Depósito esperado: ${formatCurrency(quote.expected_deposit)}`,
    `Fecha del evento: ${formatDate(eventDate)}`,
    `Hora: ${eventTime ?? 'Por confirmar'}`,
    `Dirección: ${eventAddress}`,
    `Invitados: ${guestCount ?? 'Por confirmar'}`,
    `Servicio: ${serviceLabel}`,
    paymentLink ? `Pago en línea (${paymentModeLabel}): ${paymentLink.external_url}` : 'Pago en línea: solicítanos tu link de pago respondiendo este correo.',
    `Monto del paso actual: ${paymentLink ? paymentAmount : paymentRequest.amountToChargeLabel}`,
    `Saldo restante estimado: ${formatCurrency(quote.estimated_balance)}`,
    `Pago por Zelle: ${branding.zelleInstructions}`,
    branding.zelleRecipientName ? `Receptor Zelle: ${branding.zelleRecipientName}` : null,
    branding.zelleRecipientContact ? `Dato Zelle: ${branding.zelleRecipientContact}` : null,
    `Sitio web: ${branding.websiteUrl}`,
    `Equipo ${branding.companyName}`,
  ].filter(Boolean).join('\n');

  const effectivePaymentLinkStatus = paymentLink ? paymentLinkStatus : 'missing';

  return {
    toEmail,
    recipientName,
    subject,
    html,
    text,
    bodyPreview: text.slice(0, 500),
    quoteSummary: {
      subtotal: Number(quote.subtotal ?? 0),
      discountAmount: Number(quote.discount_amount ?? 0),
      totalAmount: Number(quote.total_amount ?? 0),
      expectedDeposit: Number(quote.expected_deposit ?? 0),
    },
    eventDetails: {
      date: formatDate(eventDate),
      time: eventTime ?? 'Por confirmar',
      address: eventAddress,
      serviceLabel,
    },
    paymentLink: paymentLink
      ? {
          url: paymentLink.external_url,
          modeLabel: paymentModeLabel,
          amountToCharge: paymentAmount,
          isAutoGenerated: isAutoGeneratedLink,
        }
      : null,
    paymentLinkStatus: effectivePaymentLinkStatus,
    paymentRequest: {
      mode: paymentRequest.mode,
      modeLabel: paymentRequest.modeLabel,
      amountLabel: paymentRequest.amountToChargeLabel,
      estimatedBalanceLabel: formatCurrency(quote.estimated_balance),
    },
    branding: {
      companyName: branding.companyName,
      websiteUrl: branding.websiteUrl,
      logoUrl: branding.logoUrl,
    },
    zelle: {
      recipientName: branding.zelleRecipientName,
      recipientContact: branding.zelleRecipientContact,
      instructions: branding.zelleInstructions,
    },
  };
}

export function validateQuoteEmailDraftRequirements(draft: QuoteEmailDraft) {
  const missing: string[] = [];

  if (!draft.toEmail) missing.push('Email del cliente');
  if (draft.toEmail && !isValidEmail(draft.toEmail)) missing.push('Formato de email válido');
  if (!draft.subject.trim()) missing.push('Asunto del email');
  if (!draft.quoteSummary.totalAmount || draft.quoteSummary.totalAmount <= 0) missing.push('Total de cotización válido');

  return missing;
}
