export interface QuoteEmailDeliveryRecord {
  id: string;
  quote_id: string;
  to_email: string;
  subject: string;
  body_preview: string | null;
  payment_link_id: string | null;
  status: 'sent' | 'failed';
  error_message: string | null;
  provider: string;
  provider_message_id: string | null;
  sent_by: string;
  sent_at: string | null;
  created_at: string;
}

export interface QuoteManualDeliveryRecord {
  id: string;
  quote_id: string;
  channel: 'whatsapp' | 'sms' | 'manual_link';
  payment_mode: 'deposit' | 'full';
  payment_link_id: string | null;
  link_url: string;
  amount_to_charge: number | string | null;
  executed_by: string;
  created_at: string;
}

export interface QuoteEmailDraft {
  toEmail: string;
  recipientName: string;
  subject: string;
  html: string;
  text: string;
  bodyPreview: string;
  quoteSummary: {
    subtotal: number;
    discountAmount: number;
    totalAmount: number;
    expectedDeposit: number;
  };
  eventDetails: {
    date: string;
    time: string;
    address: string;
    serviceLabel: string;
  };
  paymentLink: {
    url: string;
    modeLabel: string;
    amountToCharge: string;
    isAutoGenerated: boolean;
  } | null;
  paymentLinkStatus: 'existing' | 'auto_generated' | 'missing';
  paymentRequest: {
    mode: 'deposit' | 'full';
    modeLabel: string;
    amountLabel: string;
    estimatedBalanceLabel: string;
  };
  branding: {
    companyName: string;
    websiteUrl: string;
    logoUrl: string | null;
  };
  zelle: {
    recipientName: string | null;
    recipientContact: string | null;
    instructions: string;
  };
}
