import type { PermissionKey } from '@/types/auth';

export const PERMISSION_LABELS: Record<PermissionKey, string> = {
  'dashboard.view': 'Dashboard',
  'crm.view': 'CRM y clientes',
  'quotes.view': 'Cotizaciones',
  'events.view': 'Reservas y eventos',
  'tasks.view': 'Tareas',
  'tasks.manage': 'Tareas: gestionar',
  'tasks.assign': 'Tareas: asignar responsables',
  'tasks.update_status': 'Tareas: actualizar estado',
  'chat.view': 'Chat: ver conversaciones',
  'chat.send': 'Chat: enviar mensajes',
  'chat.manage': 'Chat: administrar canales',
  'notifications.view': 'Notificaciones',
  'communication.view': 'Comunicación',
  'employees.view': 'Empleados',
  'finance.view': 'Finanzas',
  'finance.manage_defaults': 'Finanzas: administrar defaults',
  'finance.edit_quote_sheet': 'Finanzas: editar hoja por cotización',
  'finance.view_event_summary': 'Finanzas: ver resumen en eventos',
  'finance.invoices.view': 'Finanzas: ver invoices',
  'finance.invoices.manage': 'Finanzas: gestionar invoices',
  'finance.expenses.view': 'Finanzas: ver gastos',
  'finance.expenses.manage': 'Finanzas: gestionar gastos',
  'finance.expenses.approve': 'Finanzas: aprobar gastos',
  'inventory.view': 'Inventario',
  'inventory.manage': 'Inventario: administrar catálogo',
  'inventory.prepare': 'Inventario: preparar materiales por evento',
  'inventory.templates.view': 'Inventario: ver listas maestras por barra',
  'inventory.templates.manage': 'Inventario: gestionar listas maestras por barra',
  'settings.view': 'Configuración general',
  'audit.view': 'Auditoría',
  'admin.users.manage': 'Administrar usuarios',
};

export const PERMISSION_DESCRIPTIONS: Record<PermissionKey, string> = {
  'dashboard.view': 'Ver el tablero principal de operación interna.',
  'crm.view': 'Entrar a leads, clientes y flujo comercial base.',
  'quotes.view': 'Consultar y trabajar cotizaciones.',
  'events.view': 'Ver reservas, pre-eventos y eventos.',
  'tasks.view': 'Acceso al módulo de tareas.',
  'tasks.manage': 'Crear y editar tareas operativas.',
  'tasks.assign': 'Reasignar tareas a responsables internos permitidos.',
  'tasks.update_status': 'Actualizar estado operativo de tareas sin editar toda la tarea.',
  'chat.view': 'Acceso al chat híbrido (global y por evento).',
  'chat.send': 'Publicar mensajes en conversaciones permitidas.',
  'chat.manage': 'Activar/desactivar conversaciones de chat.',
  'notifications.view': 'Acceso al centro de notificaciones.',
  'communication.view': 'Acceso al área de comunicación interna.',
  'employees.view': 'Acceso al módulo de empleados cuando exista.',
  'finance.view': 'Ver el módulo financiero base.',
  'finance.manage_defaults': 'Administrar defaults globales de finanzas.',
  'finance.edit_quote_sheet': 'Editar hojas financieras ligadas a cotizaciones.',
  'finance.view_event_summary': 'Ver resumen financiero read-only en detalle de eventos.',
  'finance.invoices.view': 'Ver invoices emitidas desde cotizaciones aceptadas y su trazabilidad.',
  'finance.invoices.manage': 'Emitir y gestionar invoices internas desde cotizaciones aceptadas.',
  'finance.expenses.view': 'Ver gastos/spending transaccional dentro del módulo financiero.',
  'finance.expenses.manage': 'Crear, editar y enviar gastos para revisión/aprobación.',
  'finance.expenses.approve': 'Aprobar o rechazar gastos enviados en el submódulo de spending.',
  'inventory.view': 'Acceso al módulo de inventario.',
  'inventory.manage': 'Crear/editar items del catálogo de inventario.',
  'inventory.prepare': 'Actualizar conteo/estado de preparación de materiales por evento.',
  'inventory.templates.view': 'Ver listas maestras reutilizables por barra.',
  'inventory.templates.manage': 'Crear/editar/aplicar listas maestras por barra.',
  'settings.view': 'Acceso a configuración avanzada del sistema.',
  'audit.view': 'Acceso a auditoría cuando se implemente.',
  'admin.users.manage': 'Gestionar usuarios, roles y overrides de permisos.',
};

export const USER_MANAGEMENT_OVERRIDE_OPTIONS: PermissionKey[] = [
  'finance.view',
  'finance.manage_defaults',
  'finance.edit_quote_sheet',
  'finance.view_event_summary',
  'finance.invoices.view',
  'finance.invoices.manage',
  'finance.expenses.view',
  'finance.expenses.manage',
  'finance.expenses.approve',
  'crm.view',
  'quotes.view',
  'events.view',
  'inventory.view',
  'inventory.manage',
  'inventory.prepare',
  'inventory.templates.view',
  'inventory.templates.manage',
  'tasks.view',
  'tasks.manage',
  'tasks.assign',
  'tasks.update_status',
  'chat.view',
  'chat.send',
  'chat.manage',
  'notifications.view',
  'settings.view',
  'admin.users.manage',
  'audit.view',
];
