import type { PermissionKey, UserRole } from '@/types/auth';

export const ROLE_LABELS: Record<UserRole, string> = {
  owner: 'Propietario',
  manager: 'Gerencia',
  empleado: 'Empleado',
};

export const ROLE_PERMISSIONS: Record<UserRole, PermissionKey[]> = {
  owner: [
    'dashboard.view',
    'crm.view',
    'quotes.view',
    'events.view',
    'tasks.view',
    'tasks.manage',
    'tasks.assign',
    'tasks.update_status',
    'chat.view',
    'chat.send',
    'chat.manage',
    'notifications.view',
    'communication.view',
    'employees.view',
    'finance.view',
    'finance.manage_defaults',
    'finance.edit_quote_sheet',
    'finance.view_event_summary',
    'finance.invoices.view',
    'finance.invoices.manage',
    'finance.expenses.view',
    'finance.expenses.manage',
    'finance.expenses.approve',
    'inventory.view',
    'inventory.manage',
    'inventory.prepare',
    'inventory.templates.view',
    'inventory.templates.manage',
    'settings.view',
    'audit.view',
    'admin.users.manage',
  ],
  manager: [
    'dashboard.view',
    'crm.view',
    'quotes.view',
    'events.view',
    'tasks.view',
    'tasks.update_status',
    'chat.view',
    'chat.send',
    'notifications.view',
    'communication.view',
    'employees.view',
    'finance.view',
    'finance.edit_quote_sheet',
    'finance.view_event_summary',
    'finance.invoices.view',
    'finance.expenses.view',
    'inventory.view',
    'inventory.manage',
    'inventory.prepare',
    'inventory.templates.view',
    'inventory.templates.manage',
  ],
  empleado: [
    'dashboard.view',
    'tasks.view',
    'tasks.update_status',
    'chat.view',
    'chat.send',
    'notifications.view',
    'communication.view',
  ],
};
